AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ../deploy/node/node_list_sha.zip
      Environment:
        Variables:
          S3_BUCKET: artifacts-7135-2626-9054-us-west-2
