AWSTemplateFormatVersion: '2010-09-09'
Description: node sample to list 50 sha
Resources:
  nodelistsha:
    Properties:
      CodeUri: s3://artifacts-7135-2626-9054-us-west-2/e1a539d0b75973d88319b921aaf0b372
      Description: node sample to list 50 sha
      Environment:
        Variables:
          S3_BUCKET: artifacts-7135-2626-9054-us-west-2
      Events:
        Api1:
          Properties:
            Method: GET
            Path: /node_list_sha
          Type: Api
      Handler: index.handler
      MemorySize: 128
      Role: arn:aws:iam::713526269054:role/lambda_basic_execution
      Runtime: nodejs6.10
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
