AWSTemplateFormatVersion: '2010-09-09'
Description: python sample to list 50 sha
Resources:
  pythonlistsha:
    Properties:
      CodeUri: s3://artifacts-7135-2626-9054-us-west-2/763560e67b0a1f0c88d9d39a941d2abb
      Description: python sample to list 50 sha
      Environment:
        Variables:
          S3_BUCKET: artifacts-7135-2626-9054-us-west-2
      Events:
        Api1:
          Properties:
            Method: GET
            Path: /python_list_sha
          Type: Api
      Handler: handler.handler
      MemorySize: 128
      Role: arn:aws:iam::713526269054:role/lambda_basic_execution
      Runtime: python3.6
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
