AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: python sample to list 50 sha
Resources:
  pythonlistsha:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.handler
      Runtime: python3.6
      CodeUri: ../deploy/python/python_list_sha.zip
      Description: python sample to list 50 sha
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          S3_BUCKET: artifacts-7135-2626-9054-us-west-2
      Role: 'arn:aws:iam::713526269054:role/lambda_basic_execution'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /python_list_sha
            Method: GET
