AWSTemplateFormatVersion: '2010-09-09'
Description: python sample to list 50 sha
Resources:
  pythonlistsha:
    Properties:
      CodeUri: s3://artifacts-7135-2626-9054-us-west-2/f047e8b6a5ed904e8dd467f28f216f01
      Description: python sample to list 50 sha
      Environment:
        Variables:
          S3_BUCKET: artifacts-7135-2626-9054-us-west-2
      Events:
        Api1:
          Properties:
            Method: ANY
            Path: /python_list_sha
          Type: Api
      Handler: index.handler
      MemorySize: 128
      Role: arn:aws:iam::713526269054:role/lambda_basic_execution
      Runtime: python3.6
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
